version: 0.2

phases:
  install:
    commands:
      - EKS_CLUSTER_NAME=my-cluster
      - AWS_REGION=us-west-2
      - echo $EKS_CLUSTER_NAME
      - aws sts get-caller-identity
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - export KUBECONFIG=$HOME/.kube/config
      - kubectl config view --minify
      - AWS_ACCESS_KEY_ID=AKIAW3MEBWTXWOAOA2D5
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=us-west-2
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region $AWS_DEFAULT_REGION
      - kubectl cluster-info
      - curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - helm repo add stable https://charts.helm.sh/stable && helm repo update
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $REPOSITORY_URI
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112725743.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=$(echo "471112725743.dkr.ecr.us-east-1.amazonaws.com/retailsolution01")
      - echo $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=$CODEBUILD_BUILD_ID}
      - echo $IMAGE_TAG
      - EKS_KUBECTL_ROLE_ARN=arn:aws:iam::471112725743:role/EksCodeBuildKubectlRole
      - echo $EKS_KUBECTL_ROLE_ARN
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      -
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Setting Environment Variables related to AWS CLI for Kube Config Setup"
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - helm upgrade helm_charts/user-service -f helm_charts/user-service/values.yaml --set image.tag=$IMAGE_TAG