apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  url: amRiYzpwb3N0Z3Jlc3FsOi8vcmV0YWlsc29sdXRpb24wMS5jaDA0YXNnYTRneGsudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvcG9zdGdyZXM=
  username: cG9zdGdyZXM=
  password: RGV2ZWxvcGVy
