apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  url: your_base64_encoded_rds_database_url_here
  username: your_base64_encoded_username_here
  password: your_base64_encoded_password_here
