CREATE TABLE USER_DB.INVOICE(
    INVOICE_ID VARCHAR(200) NOT NULL,
    USER_ID VARCHAR(200) NOT NULL,
    INVOICE_NUMBER VARCHAR(100) NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_TIME TIMESTAMP NOT NULL,
    constraint INVOICE_ID_PK primary key (INVOICE_ID),
    constraint USER_ID foreign key (USER_ID) references USER_DB.USER_RECORD(USER_ID)
);